package vault

import (
	"fmt"
	"os"
)

// GenerateHookScript returns a shell script (sh) that calls our achievement-vault
// binary with the commit message and diff summary for the given project ID.
func GenerateHookScript(projectID int) string {
	exePath, err := os.Executable()
	if err != nil {
		// Fallback if unable to determine the absolute executable path
		exePath = "achievement-vault"
	}

	return fmt.Sprintf(`#!/bin/sh
# Git post-commit hook generated by achievement-vault
# Project ID: %d

# Extract the commit message of the latest commit
COMMIT_MSG=$(git log -1 --pretty=%%B)

# Extract the list of modified files with their modification status
DIFF_SUMMARY=$(git diff-tree --no-commit-id --name-status -r HEAD)

# Run the achievement-vault collect command with gathered data
"%s" collect %d --message "$COMMIT_MSG" --diff "$DIFF_SUMMARY"
`, projectID, exePath, projectID)
}
